### PR TITLE
feat: forwarded payments

### PR DESCRIPTION
**Pull request by michielbdejong**
Work in progress, trying to get tests to pass.

### CODE REVIEW

**Comment by michielbdejong** [comment]
@sentientwaffle did I understand correctly that `curveLocal` refers to the head hop, i.e. the relation between incoming and outgoing transfer amount (regardless of final delivery amount)? If so, I think we should add `curveRemote` to refer to the tail quote, i.e. the relation between outgoing transfer amount and final delivery amount (avoiding the terms source and destination here, as they are ambiguous in our code base).

**Comment by sentientwaffle** [comment]
@michielbdejong no, `curveLocal` is just the route's curve. If `isLocal` is true, then it is identical to the head curve, otherwise it is the whole thing.

**Comment by michielbdejong** [comment]
OK, but if it is the rate between the incoming transfer and the final transfer, then how does it relate to the outgoing transfer? Because the outgoing transfer is the one for which we want to pick an amount, right?

**Comment by sentientwaffle** [comment]
I just reviewed the code -- you were right the first time, `curveLocal` is the head hop's curve.

**Review by emschwartz — APPROVED** [review]
LGTM, just make sure to fix the `ilp-packet` dependency in the `package.json` before merging

**Pull request merged**
